version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test:unit
      - run: yarn coverage:report

workflows:
  CI:
    jobs:
      - lint_and_test
